/**
 * ============================================
 * AeroNyx P2P Invite Landing (Universal Link fallback)
 * ============================================
 * File Path: app/p2p/add/page.tsx
 *
 * Creation Reason:
 *   Web fallback for AeroNyx invite Universal Links. When the app is installed and
 *   Associated Domains / App Links are verified, iOS/Android open the app directly and
 *   this page never renders. For everyone else (no app, or desktop) this page turns a
 *   shared invite into an install -> chat funnel — the core of "every chat is distribution".
 *
 * Route: /p2p/add?pubkey=<64hex>&name=<url-encoded>
 *   Must match the app link path + public/.well-known/apple-app-site-association ("/p2p/*").
 *
 * Last Modified: v1.0.0 — initial (Universal Links)
 * ============================================
 */
import { Suspense } from 'react';
import type { Metadata } from 'next';
import ClientInvite from './ClientInvite';

// Depends on query params; skip static prerender.
export const dynamic = 'force-dynamic';

// [OG] Dynamic share-preview card: personalized title with the inviter's name so the
// link renders a rich preview in iMessage / WhatsApp / Telegram / WeChat. The preview
// image itself is generated by opengraph-image.tsx (auto-injected by Next into og/twitter).
export async function generateMetadata({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}): Promise<Metadata> {
  const sp = await searchParams;
  const raw = sp.name;
  const name = (Array.isArray(raw) ? raw[0] : raw || '').trim().slice(0, 64);
  const title = name
    ? `${name} invites you to chat privately on AeroNyx`
    : 'You are invited to chat privately on AeroNyx';
  const description =
    'End-to-end encrypted chat, calls, and file transfer. No phone number, no email, no account — just tap to connect.';
  return {
    metadataBase: new URL('https://app.aeronyx.network'),
    title,
    description,
    robots: { index: false, follow: false },
    openGraph: {
      title,
      description,
      url: 'https://app.aeronyx.network/p2p/add',
      siteName: 'AeroNyx',
      type: 'website',
    },
    twitter: { card: 'summary_large_image', title, description },
  };
}

export default function P2PAddPage() {
  return (
    <Suspense fallback={null}>
      <ClientInvite />
    </Suspense>
  );
}
